### ISSUE TITLE
RFC logo: choosing the cutest pengui

### ISSUE THREAD

**Issue by bouzlibop** [africanpenguin/rico#1]
@jmacmahon, @hachreak,

It's high time we should choose the logo, for our rico :penguin:. Below I post my propositions please comment on those and leave your propositions.
1. penguin ![first](http://cdn.flaticon.com/png/256/48469.png)
2. penguin dark ![second](http://cdn.flaticon.com/png/256/52088.png)
3. penguin dark (maybe also with the negative of that) ![third](http://cdn.flaticon.com/png/256/49510.png)
4. target_1 ![fourth](https://cdn2.iconfinder.com/data/icons/flat-jewels-icon-set/128/0008_Bullseye.png)
5. target_2 ![fifth](https://cdn3.iconfinder.com/data/icons/ballicons-free/128/target.png)
6. pen ![sixth](https://cdn2.iconfinder.com/data/icons/flat-jewels-icon-set/128/0003_Marker.png)

**Comment by hachreak** [comment]
git merge penguin calendar! XD

**Comment by jmacmahon** [comment]
My vote was for number 1

**Comment by hachreak** [comment]
I like more something like:

![Image 1](https://m1.behance.net/rendition/modules/33835799/disp/254219bd43c3f25bd135dea301b9ec7c.JPG)

![Image 2](http://i00.i.aliimg.com/wsphoto/v0/32222887866/Notebook-stationery-Large-font-b-book-b-font-tsmip-thick-2014-calendar-notepad-font-b-penguin.jpg_220x220.jpg)

![Image 3](https://img1.etsystatic.com/058/0/10202835/il_340x270.679810619_delu.jpg)

**Comment by bouzlibop** [comment]
@hachreak, I like these. Today, I will try to prepare svg of the first one (as, I like it the most).

**Comment by bouzlibop** [comment]
Okay guys, our logo is ready. Check it out! :sparkles: 
FYI: I'm closing this issue. If someone has some thing against it - please reopen :bowtie: 

![Rico](https://raw.githubusercontent.com/africanpenguin/rico/master/penguin.png)

**Comment by hachreak** [comment]
@bouzlibop put the svg version in the repository! ;)

**Comment by bouzlibop** [comment]
Done.
