### ISSUE TITLE
How can I use nodejs to serve client code?

### ISSUE THREAD

**Issue by hachreak** [africanpenguin/rico#14]

**Comment by hachreak** [comment]
I need a module to serve static pages and remove the python http server.. ;)

**Comment by bouzlibop** [comment]
I think this is equivalent to python SimpleHTTPServer:
https://www.npmjs.com/package/http-server

**Comment by hachreak** [comment]
I want also use package.json to download libs instead put them here manually... :)

**Comment by hachreak** [comment]
@jmacmahon can we use `express.static` for this purpose?

See http://blog.modulus.io/nodejs-and-express-static-content

And @bouzlibop use something like `bower` to install all libraries required?
