### ISSUE TITLE
merge theme branch

### ISSUE THREAD

**Issue by hachreak** [africanpenguin/rico#2]
Hi guys,
probably I have now more free time to work on Rico! :dancers: 
@jmacmahon can you finish the enhancements in theme branch and merge in master?
(and maybe move `rico/client/mockups` to `rico/mockups`)
@jmacmahon @bouzlibop meeting? What's the next step? We needs to split our works to not overlap us.. XD

**Comment by bouzlibop** [comment]
Let's meet today and decide on the next steps.

**Comment by jmacmahon** [comment]
Good idea Adrian!
